export interface BoilerplateFile {
  path: string;
  content: string;
}

export const NEXTJS_BOILERPLATE: BoilerplateFile[] = [
  {
    path: "package.json",
    content: JSON.stringify({
      name: "nextjs-base-app",
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev --turbopack --port 8081",
        build: "next build",
        start: "next start",
        lint: "next lint"
      },
      dependencies: {
        react: "^19.0.0",
        "react-dom": "^19.0.0",
        next: "15.2.2-canary.3"
      },
      devDependencies: {
        typescript: "^5",
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        "@tailwindcss/postcss": "^4",
        tailwindcss: "^4",
        eslint: "^9",
        "eslint-config-next": "15.2.2-canary.3",
        "@eslint/eslintrc": "^3"
      }
    }, null, 2)
  },
  {
    path: "tsconfig.json",
    content: JSON.stringify({
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [
          {
            name: "next"
          }
        ],
        paths: {
          "@/*": ["./*"]
        }
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"]
    }, null, 2)
  },
  {
    path: "next.config.ts",
    content: `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
};

export default nextConfig;
`
  },
  {
    path: "eslint.config.mjs",
    content: `import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
`
  },
  {
    path: "postcss.config.mjs",
    content: `const config = {
  plugins: ["@tailwindcss/postcss"],
};

export default config;
`
  },
  {
    path: "next-env.d.ts",
    content: `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`
  },
  {
    path: "app/layout.tsx",
    content: `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
`
  },
  {
    path: "app/page.tsx",
    content: `export default function Home() {
  return (
    <div className="flex items-center justify-center min-h-screen">
      <h1 className="text-3xl font-bold">Project Initialized</h1>
    </div>
  );
}
`
  },
  {
    path: "app/globals.css",
    content: `@import "tailwindcss";

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  background: var(--background);
  color: var(--foreground);
  font-family: Arial, Helvetica, sans-serif;
}
`
  }
];

export const REACT_BOILERPLATE: BoilerplateFile[] = [
  {
    path: "package.json",
    content: JSON.stringify({
      name: "base-react-app",
      private: true,
      version: "0.0.0",
      type: "module",
      scripts: {
        dev: "vite --port 8081 --host",
        build: "tsc -b && vite build",
        lint: "eslint .",
        preview: "vite preview"
      },
      dependencies: {
        "@radix-ui/react-slot": "^1.1.2",
        "@tailwindcss/vite": "^4.0.12",
        "class-variance-authority": "^0.7.1",
        clsx: "^2.1.1",
        "lucide-react": "^0.479.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
        "tailwind-merge": "^3.0.2",
        tailwindcss: "^4.0.12",
        "tailwindcss-animate": "^1.0.7"
      },
      devDependencies: {
        "@eslint/js": "^9.21.0",
        "@types/node": "^22.13.10",
        "@types/react": "^19.0.10",
        "@types/react-dom": "^19.0.4",
        "@vitejs/plugin-react": "^4.3.4",
        eslint: "^9.21.0",
        "eslint-plugin-react-hooks": "^5.1.0",
        "eslint-plugin-react-refresh": "^0.4.19",
        globals: "^15.15.0",
        typescript: "~5.7.2",
        "typescript-eslint": "^8.24.1",
        vite: "^6.2.0"
      }
    }, null, 2)
  },
  {
    path: "tsconfig.json",
    content: JSON.stringify({
      files: [],
      references: [
        { path: "./tsconfig.app.json" },
        { path: "./tsconfig.node.json" }
      ],
      compilerOptions: {
        baseUrl: ".",
        paths: {
          "@/*": ["./src/*"]
        }
      }
    }, null, 2)
  },
  {
    path: "tsconfig.app.json",
    content: JSON.stringify({
      compilerOptions: {
        baseUrl: ".",
        paths: {
          "@/*": ["./src/*"]
        },
        tsBuildInfoFile: "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
        target: "ES2020",
        useDefineForClassFields: true,
        lib: ["ES2020", "DOM", "DOM.Iterable"],
        module: "ESNext",
        skipLibCheck: true,
        moduleResolution: "bundler",
        allowImportingTsExtensions: true,
        isolatedModules: true,
        moduleDetection: "force",
        noEmit: true,
        jsx: "react-jsx",
        strict: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noFallthroughCasesInSwitch: true,
        noUncheckedSideEffectImports: true
      },
      include: ["src"]
    }, null, 2)
  },
  {
    path: "tsconfig.node.json",
    content: JSON.stringify({
      compilerOptions: {
        tsBuildInfoFile: "./node_modules/.tmp/tsconfig.node.tsbuildinfo",
        target: "ES2022",
        lib: ["ES2023"],
        module: "ESNext",
        skipLibCheck: true,
        moduleResolution: "bundler",
        allowImportingTsExtensions: true,
        isolatedModules: true,
        moduleDetection: "force",
        noEmit: true,
        strict: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noFallthroughCasesInSwitch: true,
        noUncheckedSideEffectImports: true
      },
      include: ["vite.config.ts"]
    }, null, 2)
  },
  {
    path: "vite.config.ts",
    content: `import path from "path"
import tailwindcss from "@tailwindcss/vite"
import react from "@vitejs/plugin-react"
import { defineConfig } from "vite"

export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
})
`
  },
  {
    path: "eslint.config.js",
    content: `import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  { ignores: ['dist'] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
    },
  },
)
`
  },
  {
    path: "index.html",
    content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + React + TS</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
  },
  {
    path: "src/main.tsx",
    content: `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
`
  },
  {
    path: "src/App.tsx",
    content: `export default function App() {
  return (
    <div className="flex items-center justify-center min-h-screen">
      <h1 className="text-3xl font-bold">Vite + React App</h1>
    </div>
  );
}
`
  },
  {
    path: "src/index.css",
    content: `@import "tailwindcss";
@plugin "tailwindcss-animate";
`
  },
  {
    path: "components.json",
    content: JSON.stringify({
      $schema: "https://ui.shadcn.com/schema.json",
      style: "new-york",
      rsc: false,
      tsx: true,
      tailwind: {
        config: "",
        css: "src/index.css",
        baseColor: "neutral",
        cssVariables: true,
        prefix: ""
      },
      aliases: {
        components: "@/components",
        utils: "@/lib/utils",
        ui: "@/components/ui",
        lib: "@/lib",
        hooks: "@/hooks"
      },
      iconLibrary: "lucide"
    }, null, 2)
  }
];

export const REACT_NATIVE_BOILERPLATE: BoilerplateFile[] = [
  {
    path: "package.json",
    content: JSON.stringify({
      name: "base-rn-app",
      version: "1.0.0",
      scripts: {
        start: "expo start",
        android: "expo start --android",
        ios: "expo start --ios",
        web: "expo start --web"
      },
      dependencies: {
        expo: "~52.0.0",
        "react-native": "0.76.0"
      }
    }, null, 2)
  }
];
